### ISSUE TITLE
Center logo as requested

### ISSUE THREAD

**Issue by sawaiz** [lukazavrtanik/Albatrog#1]
Change the intro HTML section to:

```html
<!-- Intro -->
<section id="intro" class="wrapper style1 fullscreen fade-up">
	<div class="inner">
		<div class="center-logo">
			<a href="#" class="image">
				<img src="images/SiteLogo1.png" alt="" />
			</a>
		</div>
		<!-- <h1>Albatrog</h1>
						<p>Art & Engineering</p> -->
		<ul class="actions" style="justify-content:center">
			<li><a href="#featured" class="fpbutton button scrolly">Discover</a></li>
		</ul>
	</div>
</section>
```

And add in the CSS
```css
.center-logo {
	display: flex;
	align-items: center;
	justify-content: center;
}

.fpbutton {
	margin: 20px;
}
```
